In [1]:
import numpy as np

In [2]:
list = [[1,2,3],[4,5,6],[7,8,9]]

In [3]:
array = np.array(list)

In [4]:
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
array.size

9

In [6]:
array.shape

(3, 3)

In [10]:
x = array.transpose()

In [11]:
x

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [13]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [15]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
np.ones(4) * 222

array([222., 222., 222., 222.])

In [21]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [22]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [23]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
np.random.rand(10)

array([0.75069332, 0.78285133, 0.69101921, 0.96824019, 0.02073642,
       0.3318742 , 0.66608147, 0.01449075, 0.53844488, 0.36563092])

In [26]:
np.random.randn(10)

array([-0.37048001,  0.06973345, -0.53569483, -0.49172404, -0.22086181,
        1.37866493, -0.33362542, -0.32858869,  2.48329723, -0.60794047])

In [27]:
np.random.randint(1,100)

17

In [29]:
np.random.seed(555)
np.random.rand(4)

array([0.71783409, 0.04785513, 0.94447198, 0.68638004])

In [31]:
arrn = np.random.randint(0,100,25)

In [32]:
arrn.reshape(5,5)

array([[53, 96, 84, 22, 86],
       [53, 74, 85, 27, 92],
       [58,  4, 65, 20, 51],
       [77, 83, 67, 19, 87],
       [56, 81,  4, 12, 65]])

In [33]:
arrn.max()

96

In [34]:
arrn.min()

4

In [35]:
arrn.argmin()

11

In [36]:
arrn = np.random.randint(0,100,25)

In [37]:
arrn[1:4]

array([20, 27, 29])

In [38]:
import torch

In [39]:
import torchvision

In [40]:
arrm = arrn.copy()

In [41]:
arrm[:] = 44

In [42]:
arrm

array([44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44,
       44, 44, 44, 44, 44, 44, 44, 44])

In [45]:
import pandas as pd

In [47]:
d = {'a':10, 'b':20, 'c':30}

In [48]:
labels = ['a','b','c']
values = [10,20,30]

In [51]:
pd.Series(data=values, index=labels)

a    10
b    20
c    30
dtype: int64

In [52]:
ser = pd.Series([1,2,3,4],index=['USA','Japan','USSR','UK'])

In [53]:
ser['USA']

1

In [54]:
from numpy.random import randn
np.random.seed(101)
rand_mat = randn(5,4)
rand_mat

array([[ 2.70684984,  0.62813271,  0.90796945,  0.50382575],
       [ 0.65111795, -0.31931804, -0.84807698,  0.60596535],
       [-2.01816824,  0.74012206,  0.52881349, -0.58900053],
       [ 0.18869531, -0.75887206, -0.93323722,  0.95505651],
       [ 0.19079432,  1.97875732,  2.60596728,  0.68350889]])

In [59]:
df = pd.DataFrame(data=rand_mat,index='A B C D E'.split(),columns='X Y W Z'.split())

In [60]:
df

X         Y         W         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [64]:
df[['W','X']]

W         X
A  0.907969  2.706850
B -0.848077  0.651118
C  0.528813 -2.018168
D -0.933237  0.188695
E  2.605967  0.190794

In [65]:
df['N'] = df ['W'] + df['X']

In [66]:
df

X         Y         W         Z         N
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [67]:
df.drop('N',axis=1)

X         Y         W         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [68]:
df.drop('C')

X         Y         W         Z         N
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [69]:
df.loc['A']

X    2.706850
Y    0.628133
W    0.907969
Z    0.503826
N    3.614819
Name: A, dtype: float64

In [70]:
df.iloc[0]

X    2.706850
Y    0.628133
W    0.907969
Z    0.503826
N    3.614819
Name: A, dtype: float64

In [72]:
df.loc[['A','B']][['Y','Z']]

Y         Z
A  0.628133  0.503826
B -0.319318  0.605965

In [73]:
df > 0

X      Y      W      Z      N
A   True   True   True   True   True
B   True  False  False   True  False
C  False   True   True  False  False
D   True  False  False   True  False
E   True   True   True   True   True

In [74]:
df [df>0]

X         Y         W         Z         N
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118       NaN       NaN  0.605965       NaN
C       NaN  0.740122  0.528813       NaN       NaN
D  0.188695       NaN       NaN  0.955057       NaN
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [75]:
df['W'] >0

A     True
B    False
C     True
D    False
E     True
Name: W, dtype: bool

In [77]:
df[(df['W']>0) & (df['Y']>0)]

X         Y         W         Z         N
A  2.706850  0.628133  0.907969  0.503826  3.614819
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [79]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, A to E
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   X       5 non-null      float64
 1   Y       5 non-null      float64
 2   W       5 non-null      float64
 3   Z       5 non-null      float64
 4   N       5 non-null      float64
dtypes: float64(5)
memory usage: 412.0+ bytes


In [80]:
df.describe()

X         Y         W         Z         N
count  5.000000  5.000000  5.000000  5.000000  5.000000
mean   0.343858  0.453764  0.452287  0.431871  0.796145
std    1.681131  1.061385  1.454516  0.594708  2.265550
min   -2.018168 -0.758872 -0.933237 -0.589001 -1.489355
25%    0.188695 -0.319318 -0.848077  0.503826 -0.744542
50%    0.190794  0.628133  0.528813  0.605965 -0.196959
75%    0.651118  0.740122  0.907969  0.683509  2.796762
max    2.706850  1.978757  2.605967  0.955057  3.614819

In [84]:
df.dtypes

X    float64
Y    float64
W    float64
Z    float64
N    float64
dtype: object

In [88]:
Data = {'Company': ['GOOG','GOOG','MSFT','MSFT','FB','FB'], 'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],'Sales':[200,12,340,124,243,350]}

In [89]:
df=pd.DataFrame(data=Data)

In [90]:
df

Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie     12
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [92]:
df.groupby('Company').mean()

Sales
Company       
FB       296.5
GOOG     106.0
MSFT     232.0

In [93]:
df.groupby('Company').describe().transpose()

Company              FB        GOOG        MSFT
Sales count    2.000000    2.000000    2.000000
      mean   296.500000  106.000000  232.000000
      std     75.660426  132.936075  152.735065
      min    243.000000   12.000000  124.000000
      25%    269.750000   59.000000  178.000000
      50%    296.500000  106.000000  232.000000
      75%    323.250000  153.000000  286.000000
      max    350.000000  200.000000  340.000000

In [98]:
df = pd.DataFrame({'col1':[1,2,3,4], 'col2':[222,333,555,222], 'col3':['a','b','c','d']})

In [99]:
df

col1  col2 col3
0     1   222    a
1     2   333    b
2     3   555    c
3     4   222    d

In [101]:
df['col2'].unique()

array([222, 333, 555])

In [102]:
df['col2'].nunique()

3

In [104]:
df['col2'].value_counts()

222    2
333    1
555    1
Name: col2, dtype: int64

In [105]:
df[(df['col1'] > 2) & (df['col2']==222)]

col1  col2 col3
3     4   222    d

In [106]:
def times_two(number):
    return 2*number

In [107]:
df['new']=df['col1'].apply(times_two)

In [108]:
df

col1  col2 col3  new
0     1   222    a    2
1     2   333    b    4
2     3   555    c    6
3     4   222    d    8

In [110]:
df.sort_values('col2')

col1  col2 col3  new
0     1   222    a    2
3     4   222    d    8
1     2   333    b    4
2     3   555    c    6

In [112]:
df.sort_values('col2',ascending=False)

col1  col2 col3  new
2     3   555    c    6
1     2   333    b    4
0     1   222    a    2
3     4   222    d    8

In [113]:
import torch
import numpy as np

In [116]:
arr = np.array([1,2,3,4,5])

In [118]:
x = torch.from_numpy(arr)

In [119]:
type(x)

torch.Tensor

In [120]:
torch.as_tensor(arr)

tensor([1, 2, 3, 4, 5])

In [124]:
aar2d = np.arange(0,12,1)

In [125]:
aar2d = aar2d.reshape(4,3)

In [126]:
y = torch.as_tensor(aar2d)

In [127]:
y

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [128]:
aar2d[0] =2

In [129]:
aar2d

array([[ 2,  2,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [130]:
aar2d[1] = 20

In [131]:
aar2d

array([[ 2,  2,  2],
       [20, 20, 20],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [132]:
aar2d[1][1] = 112

In [133]:
aar2d

array([[  2,   2,   2],
       [ 20, 112,  20],
       [  6,   7,   8],
       [  9,  10,  11]])

In [134]:
!pwd

/Users/shirishbahirat/Documents/code/algo/algorithm
